services:
  - type: web
    name: microcreditclient
    env: node
    buildCommand: npm run webapp:build:prod
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    publish:
      path: target/classes/static
